House_price_predictor/home/home/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('predictor.urls')),
]
...
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

House_price_predictor/home/predictor/urls.py
# urls.py

from django.urls import path
from . import views

app_name = 'predictor'
urlpatterns = [
    # ... your other views and URLs ...
    # path('predict_price/', views.house_price_prediction, name='house_price_prediction'),
    # path("home", views.homepage, name="home"),
    # path("register", views.register_request, name="register"),
    path("", views.IndexView, name="index"),
    path("base", views.BaseView, name="base"),
    path('predict/', views.predict_price, name='predict_price'),
]

House_price_predictor/home/predictor/models.py
from django.db import models


# Create your models here.
class CarouselImages(models.Model):
    photo = models.ImageField(upload_to="photo", blank=True, null=True)
    description = models.CharField(max_length=300)

    def __str__(self):
        return self.description

House_price_predictor/home/predictor/views.py
from django.shortcuts import render
import numpy as np
from .models import *
from django.views.generic.base import View

def IndexView(request):
    data = CarouselImages.objects.all()
    context = {"data": data}
    return render(request, 'predictor/index.html', context)

import joblib
from django.shortcuts import render
from django.http import HttpResponse

def predict_price(request):
    model = joblib.load("/home/ubuntu/House_price_prediction/House_price_predictor/home/predictor/model.pkl")

    predicted_price = None

    if request.method == 'POST':
        try:
            overall_qual = int(request.POST.get('overall_qual'))
            grliv_area = int(request.POST.get('grliv_area'))
            garage_cars = int(request.POST.get('garage_cars'))
            total_bsmt_sf = int(request.POST.get('total_bsmt_sf'))
            first_flr_sf = int(request.POST.get('first_flr_sf'))
            full_bath = int(request.POST.get('full_bath'))
            tot_rms_abv_grd = int(request.POST.get('tot_rms_abv_grd'))
            year_built = int(request.POST.get('year_built'))

            user_input = [overall_qual, grliv_area, garage_cars, total_bsmt_sf, first_flr_sf, full_bath, tot_rms_abv_grd, year_built]
            predicted_price = model.predict([user_input])[0]
        except (ValueError, TypeError):
            predicted_price = None

    return render(request, 'predictor/predict.html', {'predicted_price': predicted_price})

def BaseView(request):
    return render(request, 'predictor/base.html')

def PredictView(request):
    return render(request, 'predictor/predict.html')

House_price_predictor/home/predictor/templates/predictor/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>DomusMeus</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css"
    />
    {% load static %}
  <link rel="stylesheet" href="{% static 'predictor/css/index.css' %}" />
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand px-lg-5 px-sm-3" href="/"><div>
                <span class="text-warning h2">DOMUS</span
                ><span class="text-light h2"> MEUS</span>
              </div></a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarTogglerDemo02"
          aria-controls="navbarTogglerDemo02"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
              <a class="nav-link px-md-5 px-sm-3" href="{% url 'predictor:predict_price' %}">Predict</a>
            </li>
            <li class="nav-item">
              <a class="nav-link px-md-5 px-sm-3" href="#">Link</a>
            </li>
            <li class="justify-content-center">
                <div class="dropdown">
                <button
                  class="btn btn-dark dropdown-toggle text-warning mx-1"
                  type="button"
                  data-bs-toggle="dropdown"
                  aria-expanded="false"
                >
                  <i class="fa fa-user"></i>
                  My Account
                </button>
                <ul class="dropdown-menu">
                  <li>
                    <a class="dropdown-item"
                      ><span class="text-uppercase">{{name}}</span></a
                    >
                  </li>
                  <li>
                    <a
                      onclick="return confirm('Are you sure you want to Logout')"
                      class="dropdown-item"
                      href="/"
                      >Logout<i class="mx-2 bi bi-box-arrow-right text-warning"></i></a
                    >
                </li>
          </ul>
        </div>
      </nav>
    </header>
    <main>{% block content %}{% endblock %}</main>
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
    crossorigin="anonymous"
  ></script>
  <script>
    // Add this line in your JavaScript after including Bootstrap JS and jQuery
    $(document).ready(function () {
      $('[data-bs-toggle="collapse"]').collapse(); <!-- Change this attribute -->
    });
  </script>
</html>

House_price_predictor/home/predictor/templates/predictor/index.html
<!-- house_price_prediction.html -->
{% extends './base.html' %}
<html>
  <head>
    <title>Domus Meus</title>
  </head>
  <body>
    {% block content %}
    <article class="row">
      <!--carousel-start-->
      <section class="">
        <div class="banner slider">
          <div
            id="carousel"
            class="carousel slide carousel-dark carousel-fade"
            data-bs-ride="carousel"
          >
            <div class="carousel-inner" data-bs-ride="carousel">
              {% for images in data %}
              <div
                class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}"
                data-bs-interval="3000"
              >
                <div class="carousel-caption align-items-center register-left">
                  <div class="col-md-12">
                    <img
                      src="http://www.ansonika.com/mavia/img/registration_bg.svg"
                      alt=""
                    />
                    <h3 class="text-white">Welcome</h3>
                    <div class="">
                      <a
                        class="btn btn-primary col-md-4 p-2 mb-3"
                        role="button"
                        href="{% url 'predictor:predict_price' %}"
                        >Predict Price</a
                      >
                    </div>
                  </div>
                </div>
                <img
                  src="{{ images.photo.url }}"
                  class="carousel-img d-block w-100 rounded"
                  alt="Los Angeles"
                />
              </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </section>
      <!--	carousel-end-->
    </article>

    {% if predicted_price %}
    <h2>Predicted House Price: ${{ predicted_price }}</h2>
    {% endif %} {% endblock %}
  </body>
</html>

House_price_predictor/home/predictor/templates/predictor/predict.html
{% extends './base.html' %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block content %}
    <main class="container d-flex justify-content-center">
    <!--    form starts-->
   <section class="col-6 d-flex justify-content-center">
    <div class="card">
      <div class="card-body">
        <div class="text-center" id="myTabContent">
          <div class="d-flex m-4">
            <h3 class="mx-auto">House Price Predictor</h3>
          </div>
            <form
              method="POST"
              action="{% url 'predictor:predict_price' %}"
              onsubmit="return validateConfirmPassword()"
              class="needs-validation"
              novalidate
            >
              {% csrf_token %}
              <div class="register-form">
                <div class="d-flex flex-column justify-content-center">
                  <div class="form-element">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text bg-warning" id="basic-addon1">Quality</span>
                        </div>
                        <input
                          required
                          type="text"
                          class="form-control"
                          name="overall_qual"
                          placeholder="1-10 *"
                        />
                        <div class="invalid-feedback">
                          Please choose a number.
                        </div>
                        <div class="valid-feedback">Looks good!</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-element">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text bg-warning" id="basic-addon1">Area (sq.ft)</span>
                        </div>
                        <input
                          required
                          type="text"
                          class="form-control"
                          name="grliv_area"
                          placeholder="Area in square feet *"
                        />
                        <div class="invalid-feedback">
                          Please choose a number.
                        </div>
                        <div class="valid-feedback">Looks good!</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-element">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text bg-warning" id="basic-addon1">Cars</span>
                        </div>
                        <input
                          required
                          type="text"
                          class="form-control"
                          name="garage_cars"
                          placeholder="number of cars in garage *"
                        />
                        <div class="invalid-feedback">
                          Please choose a number.
                        </div>
                        <div class="valid-feedback">Looks good!</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-element">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text bg-warning" id="basic-addon1">Basement</span>
                        </div>
                        <input
                          required
                          type="text"
                          class="form-control"
                          name="total_bsmt_sf"
                          placeholder="Basement area in square feet *"
                        />
                        <div class="invalid-feedback">
                          Please choose a number.
                        </div>
                        <div class="valid-feedback">Looks good!</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-element">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text bg-warning" id="basic-addon1">1st Floor</span>
                        </div>
                        <input
                          required
                          type="text"
                          class="form-control"
                          name="first_flr_sf"
                          placeholder="square Footage of 1st floor *"
                        />
                        <div class="invalid-feedback">
                          Please choose a number.
                        </div>
                        <div class="valid-feedback">Looks good!</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-element">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text bg-warning" id="basic-addon1">Bathrooms</span>
                        </div>
                        <input
                          required
                          type="text"
                          class="form-control"
                          name="full_bath"
                          placeholder="number of bathrooms *"
                        />
                        <div class="invalid-feedback">
                          Please choose a number.
                        </div>
                        <div class="valid-feedback">Looks good!</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-element">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text bg-warning" id="basic-addon1">Bedrooms</span>
                        </div>
                        <input
                          required
                          type="text"
                          class="form-control"
                          name="tot_rms_abv_grd"
                          placeholder="number of bedrooms *"
                        />
                        <div class="invalid-feedback">
                          Please choose a number.
                        </div>
                        <div class="valid-feedback">Looks good!</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-element">
                    <div class="form-group">
                      <div class="input-group">
                        <div class="input-group-prepend">
                          <span class="input-group-text bg-warning" id="basic-addon1">Year Built</span>
                        </div>
                        <input
                          required
                          type="text"
                          class="form-control"
                          name="year_built"
                          placeholder=" year of construction *"
                        />
                        <div class="invalid-feedback">
                          Please choose a number.
                        </div>
                        <div class="valid-feedback">Looks good!</div>
                      </div>
                    </div>
                  </div>
                  <div class="form-element">
                    <div class="">
                      <input
                        class="btn btn-outline-primary col-md-4 p-2 mb-3"
                        type="submit"
                        value="Predict"
                      />
                      <input
                        onclick=""
                        class="btn btn-outline-secondary col-md-4 p-2 mb-3"
                        type="reset"
                        value="Cancel"
                      />
                    </div>
                  </div>
            </form>
        </div>
      </div>
    </div>
   </section>
   <section class="col-6 d-flex flex-column justify-content-center align-items-center">
    <div>
        <h3>Predicted Result</h3>
        {% if predicted_price is not None %}
            <p>Predicted Price: Rs:{{ predicted_price }}</p>
        {% else %}
            <p>No prediction available.</p>
        {% endif %}
    </div>
  </section>
  {% endblock %}
</main>
  </body>
  <script>
    // Example starter JavaScript for disabling form submissions if there are invalid fields
    (function () {
      "use strict";
  
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.querySelectorAll(".needs-validation");
  
      // Loop over them and prevent submission
      Array.prototype.slice.call(forms).forEach(function (form) {
        form.addEventListener(
          "submit",
          function (event) {
            if (!form.checkValidity()) {
              event.preventDefault();
              event.stopPropagation();
            }
  
            form.classList.add("was-validated");
          },
          false
        );
      });
    })();
  </script>
</html>